(function($,Drupal,drupalSettings,once){'use strict';Drupal.behaviors.initColorbox={attach:function(context,settings){if(typeof $.colorbox!=='function'||typeof settings.colorbox==='undefined'){return;}
if(!$.isFunction){$.isFunction=function(obj){return typeof obj==='function'||false;};}
if(settings.colorbox.mobiledetect&&window.matchMedia){var mq=window.matchMedia('(max-device-width: '+settings.colorbox.mobiledevicewidth+')');if(mq.matches){$.colorbox.remove();return;}}
settings.colorbox.rel=function(){return $(this).data('colorbox-gallery');};settings.colorbox.html=function(){var $modalContent=$(this).find('> .modal-content');return $modalContent.length?$(this).find('> .modal-content').children().clone():false;};$(once('init-colorbox','.colorbox',context)).each(function(){var extendParams={photo:true};var title=$(this).attr('title');if(title){extendParams.title=Drupal.colorbox.sanitizeMarkup(title);}
$(this).colorbox($.extend({},settings.colorbox,extendParams));});$('.colorbox',context).colorbox({onComplete:function(e){var focus=$('#cboxContent').find('#cboxPrevious').css('display')!=='none'?$('#cboxContent').find('#cboxPrevious'):$('#cboxContent').find('#cboxClose');focus.focus();$('#cboxContent').on('keydown',function(e){var keyCode=e.keyCode||e.which;var firstElement=$('#cboxContent').find('#cboxPrevious').last().is(':focus');var lastElement=$('#cboxContent').find('#cboxClose').first().is(':focus');if(keyCode===9&&!e.shiftKey&&lastElement){e.preventDefault();$('#cboxContent').find('#cboxPrevious').first().focus();}
else if(keyCode===9&&e.shiftKey&&firstElement){e.preventDefault();$('#cboxContent').find('#cboxClose').first().focus();}});}});}};if(!Drupal.hasOwnProperty('colorbox')){Drupal.colorbox={};}
Drupal.colorbox.sanitizeMarkup=function(markup){if(typeof DOMPurify!=='undefined'){var purifyConfig={ALLOWED_TAGS:['a','b','strong','i','em','u','cite','code','br'],ALLOWED_ATTR:['href','hreflang','title','target']}
if(drupalSettings.hasOwnProperty('dompurify_custom_config')){purifyConfig=drupalSettings.dompurify_custom_config;}
return DOMPurify.sanitize(markup,purifyConfig);}
else{return Drupal.checkPlain(markup);}}})(jQuery,Drupal,drupalSettings,once);